### ISSUE TITLE
未处理的异常

### ISSUE THREAD

**Issue by hurae** [messi-wpy/TouchEventCollect#11]
The exception was not handled due to missing onError handler in the subscribe() method call.
------
调用栈如下：

     Caused by: java.io.IOException: Stream Closed
        at java.io.FileOutputStream.write(FileOutputStream.java:310)
        at java.io.FileOutputStream.write(FileOutputStream.java:296)
        at com.example.messi_lp.touchdemo.MainActivity.lambda$startGetevent$8(MainActivity.java:271)
        at com.example.messi_lp.touchdemo.-$$Lambda$MainActivity$9eMs89YTQBa3fmCbhm2T6bwaaYU.accept(lambda)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62) 
        at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52) 
        at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:308) 
        at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:228) 
        at io.reactivex.subjects.SerializedSubject.onNext(SerializedSubject.java:104) 
        at com.example.messi_lp.touchdemo.RxBus.send(RxBus.java:34) 
        at com.example.messi_lp.touchdemo.WindowChangeDetectingService.onAccessibilityEvent(WindowChangeDetectingService.java:24)

**Comment by messi-wpy** [comment]
具体场景，

**Comment by hurae** [comment]
在收集过程中。点击get event之后，连续切换窗口的过程中。并不每次都出现。我猜测可能是和不同安卓版本的权限控制机制有关。我测试的两台手机，安卓8存在这一问题，安卓7并没有出现过。我通过显式申请外部存储权限后重打包不再出现这一问题。我发现运行过程中有读写sdcard存储的操作，可能和我测试机上安装的收集键盘记录的xposed模块有关。
