### ISSUE TITLE
it crashed after send one item

### ISSUE THREAD

**Issue by hurae** [messi-wpy/TouchEventCollect#12]
Run on Android 7.1.1 API 25 within instant run.

The following is the log after click send: 

```
2019-04-03 11:38:17.446 28706-422/com.example.messi_lp.touchdemo I/SHELL: apply: systemui
2019-04-03 11:38:17.447 28706-422/com.example.messi_lp.touchdemo I/SHELL: apply: controlbp
2019-04-03 11:38:17.447 28706-422/com.example.messi_lp.touchdemo I/SHELL: apply: trebuchet
2019-04-03 11:38:17.448 28706-422/com.example.messi_lp.touchdemo I/SHELL: apply: chrome
2019-04-03 11:38:17.449 28706-422/com.example.messi_lp.touchdemo I/SHELL: apply: settings
2019-04-03 11:38:17.449 28706-422/com.example.messi_lp.touchdemo I/SHELL: apply: packageinstaller
2019-04-03 11:38:17.449 28706-422/com.example.messi_lp.touchdemo I/SHELL: apply: latin
2019-04-03 11:38:17.449 28706-422/com.example.messi_lp.touchdemo I/SHELL: apply: supersu
2019-04-03 11:38:17.449 28706-422/com.example.messi_lp.touchdemo I/SHELL: apply: touchdemo
2019-04-03 11:38:17.449 28706-422/com.example.messi_lp.touchdemo I/SHELL: apply: flatMap 1
2019-04-03 11:38:17.452 28706-422/com.example.messi_lp.touchdemo I/SHELL: buttonInit: flatMap 2
2019-04-03 11:38:17.526 28706-422/com.example.messi_lp.touchdemo D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2019-04-03 11:38:17.697 28706-422/com.example.messi_lp.touchdemo D/OkHttp: --> POST http://119.23.79.87:5555/api/test/post/
2019-04-03 11:38:17.698 28706-422/com.example.messi_lp.touchdemo D/OkHttp: Content-Type: application/json; charset=utf-8
2019-04-03 11:38:17.698 28706-422/com.example.messi_lp.touchdemo D/OkHttp: Content-Length: 2956
2019-04-03 11:38:17.700 28706-422/com.example.messi_lp.touchdemo D/OkHttp: {"List":[[{"statu":0,"time":8192913379725,"x":720,"y":1617},{"statu":0,"time":8192920002799,"x":736,"y":1588},{"statu":0,"time":8192926368269,"x":754,"y":1545},{"statu":0,"time":8192932221758,"x":770,"y":1464},{"statu":0,"time":8192935838008,"x":794,"y":1401},{"statu":0,"time":8192938330195,"x":819,"y":1314},{"statu":0,"time":8192955369417,"x":843,"y":1225},{"statu":0,"time":8193807913512,"x":893,"y":1114},{"statu":0,"time":8193811145335,"x":932,"y":1014},{"statu":0,"time":8193813895388,"x":978,"y":901}],[{"statu":0,"time":8193819913983,"x":638,"y":1745},{"statu":0,"time":8193826626327,"x":646,"y":1724},{"statu":0,"time":8193829885129,"x":659,"y":1694},{"statu":0,"time":8193835526118,"x":670,"y":1650},{"statu":0,"time":8193840139661,"x":687,"y":1604},{"statu":0,"time":8193842708256,"x":710,"y":1531},{"statu":0,"time":8194790266266,"x":742,"y":1447},{"statu":0,"time":8194791964130,"x":767,"y":1358},{"statu":0,"time":8194796302465,"x":808,"y":1229},{"statu":0,"time":8194799980747,"x":854,"y":1112},{"statu":0,"time":8194805658039,"x":923,"y":954},{"statu":0,"time":8194807557050,"x":996,"y":804}],[{"statu":0,"time":8194813518456,"x":597,"y":1836},{"statu":0,"time":8194816807519,"x":604,"y":1816},{"statu":0,"time":8194823552572,"x":614,"y":1787},{"statu":0,"time":8196210417971,"x":630,"y":1751},{"statu":0,"time":8196215611461,"x":652,"y":1692},{"statu":0,"time":8196217984795,"x":670,"y":1625},{"statu":0,"time":8196220405472,"x":695,"y":1539},{"statu":0,"time":8196222656149,"x":717,"y":1461},{"statu":0,"time":8196225360679,"x":759,"y":1328},{"statu":0,"time":8196227150055,"x":800,"y":1222},{"statu":0,"time":8196231107035,"x":863,"y":1059},{"statu":0,"time":8196234089171,"x":934,"y":882}],[{"statu":0,"time":8259557801938,"x":744,"y":1218},{"statu":0,"time":8259682288408,"x":732,"y":1244},{"statu":0,"time":8259685121846,"x":715,"y":1287},{"statu":0,"time":8259687081273,"x":705,"y":1314},{"statu":0,"time":8259688710127,"x":696,"y":1338},{"statu":0,"time":8259690957835,"x":683,"y":1371},{"statu":0,"time":8259696685597,"x":672,"y":1412},{"statu":0,"time":8259698901222,"x":657,"y":1450}],[{"statu":0,"time":8267387745894,"x":660,"y":1365}],[{"statu":0,"time":8272193894133,"x":269,"y":2020}],[{"statu":0,"time":8294854628110,"x":719,"y":1342},{"statu":0,"time":8295331321074,"x":712,"y":1362},{"statu":0,"time":8295334509564,"x":704,"y":1388},{"statu":0,"time":8295338678263,"x":689,"y":1419},{"statu":0,"time":8295341940033,"x":674,"y":1453},{"statu":0,"time":8295343927012,"x":655,"y":1487},{"statu":0,"time":8295345939252,"x":637,"y":1520}],[{"statu":0,"time":8296166607876,"x":713,"y":1382},{"statu":0,"time":8296169476991,"x":707,"y":1406},{"statu":0,"time":8296172689909,"x":696,"y":1445},{"statu":0,"time":8296175026523,"x":681,"y":1486},{"statu":0,"time":8296177876106,"x":662,"y":1530},{"statu":0,"time":8296180058658,"x":647,"y":1582}],[{"statu":0,"time":8296184037877,"x":850,"y":1095}]],"appName":"systemui","userID":0}
2019-04-03 11:38:17.700 28706-422/com.example.messi_lp.touchdemo D/OkHttp: --> END POST (2956-byte body)
2019-04-03 11:38:18.904 19431-19466/system_process D/LuxLevels: bright hysteresis constant= 0.1, threshold=72.71172, lux=66.10156
2019-04-03 11:38:18.904 19431-19466/system_process D/LuxLevels: dark hysteresis constant= 0.2, threshold=52.881252, lux=66.10156
2019-04-03 11:38:24.123 19431-19587/system_process D/WifiStateMachine: updateCapabilities for config:CCNU-AUTOfalse,false
2019-04-03 11:38:24.150 21145-21145/com.halo.wifikey.wifilocating W/WifiApp: [WkMessager.java,83,onReceive] android.net.wifi.RSSI_CHANGED
2019-04-03 11:38:25.066 28706-422/com.example.messi_lp.touchdemo D/OkHttp: <-- HTTP FAILED: java.net.SocketException: Connection reset
2019-04-03 11:38:25.086 28706-28706/com.example.messi_lp.touchdemo W/System.err: java.net.SocketException: Connection reset
2019-04-03 11:38:25.090 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:192)
2019-04-03 11:38:25.091 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:120)
2019-04-03 11:38:25.092 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at okio.Okio$2.read(Okio.java:140)
2019-04-03 11:38:25.093 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
2019-04-03 11:38:25.094 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:354)
2019-04-03 11:38:25.095 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:226)
2019-04-03 11:38:25.096 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
2019-04-03 11:38:25.097 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
2019-04-03 11:38:25.099 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
2019-04-03 11:38:25.100 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-04-03 11:38:25.101 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
2019-04-03 11:38:25.102 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-04-03 11:38:25.103 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-04-03 11:38:25.104 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
2019-04-03 11:38:25.105 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-04-03 11:38:25.106 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-04-03 11:38:25.107 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
2019-04-03 11:38:25.108 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-04-03 11:38:25.109 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
2019-04-03 11:38:25.110 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-04-03 11:38:25.111 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-04-03 11:38:25.112 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:213)
2019-04-03 11:38:25.113 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-04-03 11:38:25.113 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-04-03 11:38:25.113 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
2019-04-03 11:38:25.113 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at okhttp3.RealCall.execute(RealCall.java:92)
2019-04-03 11:38:25.114 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at com.example.messi_lp.touchdemo.FileConvert.upLoad(FileConvert.java:59)
2019-04-03 11:38:25.114 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at com.example.messi_lp.touchdemo.MainActivity.lambda$null$5(MainActivity.java:224)
2019-04-03 11:38:25.114 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at com.example.messi_lp.touchdemo.-$$Lambda$MainActivity$7lcn4AekQHmvOcbEceAA9mjJMPw.apply(lambda)
2019-04-03 11:38:25.114 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:121)
2019-04-03 11:38:25.115 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drainLoop(ObservableFlatMap.java:437)
2019-04-03 11:38:25.115 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drain(ObservableFlatMap.java:326)
2019-04-03 11:38:25.115 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap$InnerObserver.onSubscribe(ObservableFlatMap.java:548)
2019-04-03 11:38:25.116 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at io.reactivex.internal.operators.observable.ObservableFromIterable.subscribeActual(ObservableFromIterable.java:55)
2019-04-03 11:38:25.116 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12197)
2019-04-03 11:38:25.116 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.subscribeInner(ObservableFlatMap.java:165)
2019-04-03 11:38:25.117 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onNext(ObservableFlatMap.java:139)
2019-04-03 11:38:25.117 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
2019-04-03 11:38:25.117 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onNext(ObservableCreate.java:66)
2019-04-03 11:38:25.117 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at com.example.messi_lp.touchdemo.MainActivity$2.subscribe(MainActivity.java:201)
2019-04-03 11:38:25.118 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
2019-04-03 11:38:25.118 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12197)
2019-04-03 11:38:25.118 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
2019-04-03 11:38:25.118 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
2019-04-03 11:38:25.119 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2019-04-03 11:38:25.119 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2019-04-03 11:38:25.119 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
2019-04-03 11:38:25.120 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
2019-04-03 11:38:25.120 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2019-04-03 11:38:25.120 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2019-04-03 11:38:25.120 28706-28706/com.example.messi_lp.touchdemo W/System.err:     at java.lang.Thread.run(Thread.java:761)
```

**Comment by hurae** [comment]
After crash the function of getevent didn't restart automatically. It simply act out no response.

After terminate the process and start app manually, the getevent works again but failed again with exactly the same error.
