### ISSUE TITLE
parseInt error

### ISSUE THREAD

**Issue by hurae** [messi-wpy/TouchEventCollect#16]
The related part of event file is:
```
245028476701237(837,1094)
action_down 
action_up
245028480186966(567,1694)
action_down 
action_up 
com. android. providers. downloads mark. via
245046595026490(-1726,9999)
action_up
245046599886386(886,1698)
action_down action_up
245046605435605(191,1709)
action_down
```
The exception occurs at line `245046595026490(-1726,9999)`, when try to deal with `-1726`

The related code is:
`data.setX(Integer.parseInt(elem[1]));`

The log is following:
```
2019-04-03 14:01:50.644 14845-14845/com.example.messi_lp.touchdemo W/System.err: java.lang.NumberFormatException: For input string: ""
2019-04-03 14:01:50.658 14845-14845/com.example.messi_lp.touchdemo W/System.err:     at java.lang.Integer.parseInt(Integer.java:533)
2019-04-03 14:01:50.659 14845-14845/com.example.messi_lp.touchdemo W/System.err:     at java.lang.Integer.parseInt(Integer.java:556)
2019-04-03 14:01:50.659 14845-14845/com.example.messi_lp.touchdemo W/System.err:     at com.example.messi_lp.touchdemo.FileConvert.readFromFile(FileConvert.java:106)
2019-04-03 14:01:50.659 14845-14845/com.example.messi_lp.touchdemo W/System.err:     at com.example.messi_lp.touchdemo.MainActivity$2.subscribe(MainActivity.java:200)
2019-04-03 14:01:50.659 14845-14845/com.example.messi_lp.touchdemo W/System.err:     at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
2019-04-03 14:01:50.659 14845-14845/com.example.messi_lp.touchdemo W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12197)
2019-04-03 14:01:50.659 14845-14845/com.example.messi_lp.touchdemo W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
2019-04-03 14:01:50.659 14845-14845/com.example.messi_lp.touchdemo W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
2019-04-03 14:01:50.659 14845-14845/com.example.messi_lp.touchdemo W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2019-04-03 14:01:50.659 14845-14845/com.example.messi_lp.touchdemo W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2019-04-03 14:01:50.659 14845-14845/com.example.messi_lp.touchdemo W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
2019-04-03 14:01:50.659 14845-14845/com.example.messi_lp.touchdemo W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
2019-04-03 14:01:50.659 14845-14845/com.example.messi_lp.touchdemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2019-04-03 14:01:50.659 14845-14845/com.example.messi_lp.touchdemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2019-04-03 14:01:50.659 14845-14845/com.example.messi_lp.touchdemo W/System.err:     at java.lang.Thread.run(Thread.java:760)
```

**Comment by hurae** [comment]
I think simply ignore such kind of number is ok
